config/routes.rb
RailsReviews::Application.routes.draw do
  resources :reviews

  resources :restaurants do
    resources :reviews
  end

  root :to => 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	has_many :reviews

	def average_stars
		self.reviews.average(:stars)
	end
	
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :restaurant
	validates :stars, numericality: { :greater_than_or_equal_to => 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(params.require(:restaurant).permit(:name, :phone))
		if @restaurant.save
			redirect_to restaurants_url
		else
			render action: "new"
		end
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])

		if @restaurant.update_attributes(params.require(:restaurant).permit(:name, :phone))
			redirect_to restaurants_path
		else
			render action: "edit"
		end
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		redirect_to restaurants_url
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@review = @restaurant.reviews.new(params.require(:review).permit(:description, :stars))
		if @review.save
			redirect_to restaurant_url(@restaurant)
		else
			flash[:error] = @review.errors.full_messages
			redirect_to restaurant_url(@restaurant)
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsReviews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
<%= yield %>
	</div>

</body>
</html>

app/views/restaurants/edit.html.erb
<h2>Edit <%= @restaurant.name %></h2>

<%= form_for @restaurant do |form| %>
	<div>
		<%= form.label :name %><br />
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.label :phone %><br />
		<%= form.text_field :phone %>
	</div>

	<p><%= form.submit %></p>
<% end %>

app/views/restaurants/index.html.erb
<div class="jumbotron">
	<h1>Rails Reviews</h1>
	<p>Best Restaurant Reviews in the NY Area!</p>
	<p><%= link_to "Add a Restaurant", new_restaurant_path %></p>
</div>

<table class="table table-striped">
	<thead>
		<th>Name</th>
		<th>Phone</th>
		<th>Actions</th>
	</thead>
	<tbody>
		<% @restaurants.each do |single_restaurant| %>
			<tr>
				<td><%= link_to single_restaurant.name, restaurant_path(single_restaurant) %></td>
				<td><%= single_restaurant.phone %></td>
				<td><%= link_to "Edit", edit_restaurant_path(single_restaurant) %> | 
	<%= link_to 'Destroy', single_restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
	</tbody>
</table>

<div class="footer">
	<%= link_to "Restaurants Home", restaurants_path %><br />
	Michele Lugo, January 25, 2014</div>

app/views/restaurants/new.html.erb
<h2>Create New Restaurant</h2>
<%= form_for @restaurant do |form| %>
	<div>
		<%= form.label :name %><br />
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.label :phone %><br />
		<%= form.text_field :phone %>
	</div>

	<p><%= form.submit %></p>
<% end %>

app/views/restaurants/show.html.erb
<link rel="stylesheet" type="text/css" href="style.css">

<div class="hero-unit">
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.phone %></p>
<% if @restaurant.average_stars %>
<p>Average Rating: <% (1..@restaurant.average_stars).each do |x| %>
	<span>*</span>
	 <% end %>
<% else %>
<p>No Ratings</p>
<% end %>
</p>
</div>

<% if @restaurant.reviews %>
<% @restaurant.reviews.order(:created_at).each do |single_review| %>
	<hr />
	Created Date: <%= single_review.created_at.strftime("%A, %B %d, %Y at %r") %><br />
	This user gave: <%= single_review.stars %> Stars<br />
	This user said: <%= single_review.description %>
<% end %>
<% else %>
No reviews!
<% end %>

<h2>Add Review</h2>
<p>Post your honest review about this NY Restaurant</p>

<% if flash[:error] %>
	<span color="red">Error</span>
	<% flash[:error].each do |msg| %>
	<%= msg %>
	<% end %>
<% end %>
<%= form_for [@restaurant, @restaurant.reviews.new] do |form| %>
	<%= form.label :description %>
	<%= form.text_field :description %>
	<%= form.label :stars %>
	<%= form.text_field :stars %>
	<%= form.submit %>

<% end %>

<div class="footer">
	<%= link_to "Restaurants Home", restaurants_path %><br />
Michele Lugo, January 25, 2014
</div>